version: '3.8'
services:
  postgres:
    image: postgres
    container_name: studies-database
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./.docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - '.env'
    networks:
      - backend

  api:
    image: studies/api
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      args:
        - USER_NAME=${USER:-root}
        - USER_ID=${USER_ID:-1000}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    container_name: studies_api
    stdin_open: true
    tty: true
    volumes:
      - ./:/api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - backend  
    env_file:
      - '.env'
  
  mailcatcher:
    image: schickling/mailcatcher
    networks:
      - backend
    ports:
      - "1025:1025"
      - "1080:1080"
  
  redis:
    image: 'redis'
    command: redis-server --requirepass root123
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
    networks:
      - backend
    env_file:
      - '.env'
  
  sidekiq:
    image: studies/api
    command: bundle exec sidekiq  -C config/sidekiq.yml
    container_name: studies_sidekiq
    volumes:
      - ./:/api
    depends_on:
      - api
      - postgres
      - redis
    networks:
      - backend  
    env_file:
      - '.env'

volumes:
  postgres:
  studies_api:
  redis:
networks:
  backend:
